{% set name = "einops" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b7a83cffc1ea88e306df099b7cbb9c3ba5003bd84d05ae44be5655864abb8d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - numpy

test:
  imports:
    - einops
    - einops.layers

about:
  home: https://github.com/arogozhnikov/einops
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A new flavour of deep learning operations.
  description: |
    Flexible and powerful tensor operations for readable and reliable code.
    Supports numpy, pytorch, tensorflow, and others.
  doc_url: https://github.com/arogozhnikov/einops
  dev_url: https://github.com/arogozhnikov/einops

extra:
  recipe-maintainers:
    - asford
