{% set name = "einops" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63486517fed345712a8385c100cb279108d9d47e6ae59099b07657e983deae85

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.10.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - einops
    - einops.layers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arogozhnikov/einops
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A new flavour of deep learning operations.
  description: |
    Flexible and powerful tensor operations for readable and reliable code.
    Supports numpy, pytorch, tensorflow, and others.
  doc_url: https://github.com/arogozhnikov/einops
  dev_url: https://github.com/arogozhnikov/einops

extra:
  recipe-maintainers:
    - maresb
    - asford
